import type { Post, Department, Category, State } from './types';

export const DEPARTMENTS: Department[] = [
  { id: '1', name: 'UPSC', slug: 'upsc', official_site: 'https://upsc.gov.in' },
  { id: '2', name: 'SSC', slug: 'ssc', official_site: 'https://ssc.nic.in' },
  { id: '3', name: 'IBPS', slug: 'ibps', official_site: 'https://ibps.in' },
  { id: '4', name: 'RRB', slug: 'rrb', official_site: 'https://indianrailways.gov.in' },
  { id: '5', name: 'SBI', slug: 'sbi', official_site: 'https://sbi.co.in' },
  { id: '6', name: 'DRDO', slug: 'drdo', official_site: 'https://drdo.gov.in' },
  { id: '7', name: 'ISRO', slug: 'isro', official_site: 'https://isro.gov.in' },
  { id: '8', name: 'NTPC', slug: 'ntpc', official_site: 'https://ntpc.co.in' },
];

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Banking', slug: 'banking', color: '#1d4ed8' },
  { id: '2', name: 'Defence', slug: 'defence', color: '#15803d' },
  { id: '3', name: 'Railways', slug: 'railways', color: '#7e22ce' },
  { id: '4', name: 'Teaching', slug: 'teaching', color: '#be123c' },
  { id: '5', name: 'PSU', slug: 'psu', color: '#0369a1' },
  { id: '6', name: 'Police', slug: 'police', color: '#a16207' },
  { id: '7', name: 'Health', slug: 'health', color: '#16a34a' },
  { id: '8', name: 'State PSC', slug: 'state-psc', color: '#c2410c' },
];

export const STATES: State[] = [
  { id: '1', name: 'Uttar Pradesh', slug: 'uttar-pradesh', code: 'UP' },
  { id: '2', name: 'Rajasthan', slug: 'rajasthan', code: 'RJ' },
  { id: '3', name: 'Bihar', slug: 'bihar', code: 'BR' },
  { id: '4', name: 'Maharashtra', slug: 'maharashtra', code: 'MH' },
  { id: '5', name: 'Madhya Pradesh', slug: 'madhya-pradesh', code: 'MP' },
  { id: '6', name: 'Gujarat', slug: 'gujarat', code: 'GJ' },
  { id: '7', name: 'Tamil Nadu', slug: 'tamil-nadu', code: 'TN' },
  { id: '8', name: 'Karnataka', slug: 'karnataka', code: 'KA' },
  { id: '9', name: 'West Bengal', slug: 'west-bengal', code: 'WB' },
  { id: '10', name: 'Haryana', slug: 'haryana', code: 'HR' },
  { id: '11', name: 'Delhi', slug: 'delhi', code: 'DL' },
  { id: '12', name: 'Punjab', slug: 'punjab', code: 'PB' },
];

export const MOCK_POSTS: Post[] = [
  {
    id: '1',
    slug: 'upsc-civil-services-2025-notification',
    title: 'UPSC Civil Services 2025 Notification — 1056 Posts',
    post_type: 'job',
    status: 'published',
    department: DEPARTMENTS[0],
    category: CATEGORIES[4],
    states: [],
    total_vacancies: 1056,
    application_start: '2025-02-05',
    application_end: '2025-03-04',
    exam_date: '2025-05-25',
    description: 'Union Public Service Commission has released the official notification for Civil Services Examination 2025. This is one of the most prestigious examinations in India for recruitment to various Group A and Group B services.',
    important_dates: [
      { label: 'Notification Date', date: '2025-02-05' },
      { label: 'Application Start', date: '2025-02-05' },
      { label: 'Last Date to Apply', date: '2025-03-04' },
      { label: 'Prelims Exam', date: '2025-05-25' },
    ],
    eligibility: [
      { label: 'Age Limit', value: '21 to 32 years (relaxation applicable)' },
      { label: 'Qualification', value: "Bachelor's Degree in any discipline" },
      { label: 'Nationality', value: 'Indian Citizen' },
    ],
    salary_range: { min: 56100, max: 250000, text: '₹56,100 – ₹2,50,000 (Level 10–18)' },
    is_featured: true,
    is_trending: true,
    view_count: 48520,
    published_at: '2025-02-05T09:00:00Z',
    updated_at: '2025-02-05T09:00:00Z',
    source_url: 'https://upsc.gov.in',
  },
  {
    id: '2',
    slug: 'ssc-cgl-2025-recruitment',
    title: 'SSC CGL 2025 Recruitment — 17727 Combined Graduate Level Posts',
    post_type: 'job',
    status: 'published',
    department: DEPARTMENTS[1],
    category: CATEGORIES[4],
    states: [],
    total_vacancies: 17727,
    application_start: '2025-06-09',
    application_end: '2025-07-07',
    exam_date: '2025-09-13',
    description: 'Staff Selection Commission has released Combined Graduate Level 2025 notification for 17727 vacancies across various ministries, departments, and organizations of the Government of India.',
    important_dates: [
      { label: 'Application Start', date: '2025-06-09' },
      { label: 'Last Date', date: '2025-07-07' },
      { label: 'Tier I Exam', date: '2025-09-13' },
    ],
    eligibility: [
      { label: 'Age Limit', value: '18 to 32 years' },
      { label: 'Qualification', value: "Bachelor's Degree" },
    ],
    salary_range: { text: '₹25,500 – ₹1,51,100 (Pay Level 4–8)' },
    is_featured: true,
    is_trending: true,
    view_count: 62450,
    published_at: '2025-06-09T08:30:00Z',
    updated_at: '2025-06-09T08:30:00Z',
  },
  {
    id: '3',
    slug: 'ibps-po-2025-recruitment',
    title: 'IBPS PO 2025 — Probationary Officer 4455 Posts',
    post_type: 'job',
    status: 'published',
    department: DEPARTMENTS[2],
    category: CATEGORIES[0],
    states: [],
    total_vacancies: 4455,
    application_start: '2025-08-01',
    application_end: '2025-08-21',
    exam_date: '2025-10-11',
    description: 'Institute of Banking Personnel Selection invites online applications for recruitment of Probationary Officers (PO) in Participating Banks. Selection through Prelims, Mains and Interview.',
    important_dates: [
      { label: 'Application Start', date: '2025-08-01' },
      { label: 'Last Date', date: '2025-08-21' },
      { label: 'Prelims', date: '2025-10-11' },
      { label: 'Mains', date: '2025-11-30' },
    ],
    eligibility: [
      { label: 'Age', value: '20 to 30 years' },
      { label: 'Qualification', value: "Bachelor's Degree (any discipline)" },
    ],
    salary_range: { text: '₹36,000 – ₹63,840 (with DA)' },
    is_trending: true,
    view_count: 34210,
    published_at: '2025-08-01T10:00:00Z',
    updated_at: '2025-08-01T10:00:00Z',
  },
  {
    id: '4',
    slug: 'rrb-ntpc-2025-recruitment',
    title: 'RRB NTPC 2025 — Railway Non-Technical Popular Categories 11558 Posts',
    post_type: 'job',
    status: 'published',
    department: DEPARTMENTS[3],
    category: CATEGORIES[2],
    states: [],
    total_vacancies: 11558,
    application_start: '2025-09-14',
    application_end: '2025-10-13',
    description: 'Railway Recruitment Boards have released notification for Non-Technical Popular Categories across all RRBs. Posts include Junior Clerk, Accounts Clerk, Junior Time Keeper, and more.',
    is_trending: true,
    view_count: 28900,
    published_at: '2025-09-14T08:00:00Z',
    updated_at: '2025-09-14T08:00:00Z',
  },
  {
    id: '5',
    slug: 'ssc-cgl-2024-result-declared',
    title: 'SSC CGL 2024 Final Result Declared — Download Marks & Rank',
    post_type: 'result',
    status: 'published',
    department: DEPARTMENTS[1],
    category: CATEGORIES[4],
    states: [],
    description: 'Staff Selection Commission has declared the final result for Combined Graduate Level 2024 examination. Candidates can download the merit list and check their marks and rank.',
    is_trending: true,
    view_count: 55600,
    published_at: '2025-01-15T12:00:00Z',
    updated_at: '2025-01-15T12:00:00Z',
  },
  {
    id: '6',
    slug: 'ibps-po-2025-admit-card',
    title: 'IBPS PO 2025 Prelims Admit Card Released — Download Now',
    post_type: 'admit_card',
    status: 'published',
    department: DEPARTMENTS[2],
    category: CATEGORIES[0],
    states: [],
    description: 'IBPS has released Prelims admit card for Probationary Officer 2025. Candidates who applied can download their hall ticket using registration number and date of birth.',
    is_trending: false,
    view_count: 18400,
    published_at: '2025-09-28T11:00:00Z',
    updated_at: '2025-09-28T11:00:00Z',
  },
  {
    id: '7',
    slug: 'drdo-ceptam-10-recruitment-2025',
    title: 'DRDO CEPTAM 10 Recruitment 2025 — 1901 Technical Posts',
    post_type: 'job',
    status: 'published',
    department: DEPARTMENTS[5],
    category: CATEGORIES[4],
    states: [],
    total_vacancies: 1901,
    application_start: '2025-04-10',
    application_end: '2025-05-08',
    description: 'Defence Research and Development Organisation invites applications for Centre for Personnel Talent Management (CEPTAM) for recruitment of Technician A and Admin & Allied posts.',
    is_featured: false,
    view_count: 22100,
    published_at: '2025-04-10T09:00:00Z',
    updated_at: '2025-04-10T09:00:00Z',
  },
  {
    id: '8',
    slug: 'isro-scientist-engineer-2025',
    title: 'ISRO Scientist/Engineer SC 2025 — 320 Posts, Apply Online',
    post_type: 'job',
    status: 'published',
    department: DEPARTMENTS[6],
    category: CATEGORIES[4],
    states: [],
    total_vacancies: 320,
    application_start: '2025-07-01',
    application_end: '2025-07-31',
    description: 'Indian Space Research Organisation recruits Scientist/Engineer SC in various disciplines including Electronics, Mechanical, Computer Science and other technical streams.',
    view_count: 41200,
    published_at: '2025-07-01T09:00:00Z',
    updated_at: '2025-07-01T09:00:00Z',
  },
];

export const TICKER_ITEMS = [
  '🔔 UPSC CSE 2025 Notification Out — 1056 Posts',
  '📊 SSC CGL 2024 Final Result Declared',
  '💼 RRB NTPC 2025 — Apply for 11558 Railway Posts',
  '🎫 IBPS PO 2025 Prelims Admit Card Released',
  '💼 DRDO CEPTAM 10 — 1901 Technical Posts',
  '💼 ISRO Scientist/Engineer 2025 — 320 Posts',
  '📊 SBI Clerk 2025 Mains Result Out',
];
